#skUtilities

#--------------------------------------------------------------------------

#Should this addon check for an update every 12 hours

checkForUpdates: true
downloadUpdates: false

#--------------------------------------------------------------------------

#Disables or Enables parts of the addon.
#If disabled the only way to renable is to change to true and restart the server,
#this only disables/enables those parts when you start the server.

loadConversions: true
loadFiles: true
loadUtilities: true

#--------------------------------------------------------------------------

#DO NOT CHANGE THIS!
configVersion: 1
